### ISSUE TITLE
Airdrop works?

### ISSUE THREAD

**Issue by KikeVR1996** [perez987/Intel-AX210-wifi6-on-macOS-Sonoma#3]
Hello! I saw the project, my question is if that card could work with continuity and airdrop on hackintosh. Thank you.

**Comment by perez987** [comment]
@KikeVR1996 
Airdrop doesn't work in any way. 
With itlwm.kext you don’t have any Handoff or Continuity feature. 
AirportItlwm.kext provides minimal Continuity features (Handoff and Universal Clipboard, not always available).
Buenas noches!
